const cidadesAtlas = {
  ABC: [
    "Americana",
    "Aguai",
    "Americo Brasiliense",
    "Amparo",
    "Andradina",
    "Angra Dos Reis",
    "Aracatuba",
    "Aracoiaba Da Serra",
    "Araraquara",
    "Araras",
    "Araruama",
    "Armacao Dos Buzios",
    "Atibaia",
    "Barra Mansa",
    "Barrinha",
    "Bertioga",
    "Birigui",
    "Boa Vista",
    "Boituva",
    "Braganca Paulista",
    "Cabo De Santo Agostinho",
    "Cabreuva",
    "Cacapava",
    "Campos Do Jordao",
    "Caraguatatuba",
    "Cordeiropolis",
    "Cravinhos",
    "Cubatao",
    "Descalvado",
    "Diadema",
    "Espirito Santo Do Pinhal",
    "Goiana",
    "Guaruja",
    "Hortolandia",
    "Ipero",
    "Itanhaem",
    "Itapetininga",
    "Itapeva",
    "Itapira",
    "Itu",
    "Ituverava",
    "Jaboatao Dos Guararapes",
    "Jacarei",
    "Jaguariuna",
    "Jales",
    "Jarinu",
    "Leme",
    "Limeira",
    "Lins",
    "Lucas Do Rio Verde",
    "Mairinque",
    "Mairipora",
    "Manaus",
    "Mangaratiba",
    "Matao",
    "Maua",
    "Mirassol",
    "Mogi Das Cruzes",
    "Mogi Guacu",
    "Mogi Mirim",
    "Mongagua",
    "Nova Mutum",
    "Olinda",
    "Orlandia",
    "Ourinhos",
    "Paulista",
    "Pedreira",
    "Penapolis",
    "Pereira Barreto",
    "Peruibe",
    "Petrolina",
    "Pindamonhangaba",
    "Piracaia",
    "Pirassununga",
    "Porto Real",
    "Praia Grande",
    "Recife",
    "Resende",
    "Rio Claro",
    "Rio Grande Da Serra",
    "Salto De Pirapora",
    "Santa Barbara Doeste",
    "Santa Branca",
    "Santa Cruz Do Rio Pardo",
    "Santa Gertrudes",
    "Santa Isabel",
    "Santo Andre",
    "Santos Abc",
    "Sao Bernardo Do Campo",
    "Sao Caetano Do Sul",
    "Sao Joao Da Boa Vista",
    "Sao Joaquim Da Barra",
    "Sao Jose Dos Campos",
    "Sao Sebastiao",
    "Sao Vicente",
    "Serra Negra",
    "Sumare",
    "Taubate",
    "Timoteo",
    "Tres Lagoas",
    "Ubatuba",
  ],
  SP: ["Sao Paulo"],
  BH: ["Belo Horizonte"],
  SANTOS: [
    "Aguas Lindas De Goias",
    "Anapolis",
    "Belo Horizonte",
    "Brasilia",
    "Caldas Novas",
    "Catalao",
    "Cidade Ocidental",
    "Formosa",
    "Goiania",
    "Ibirite",
    "Itabira",
    "Itaborai",
    "Itumbiara",
    "Jatai",
    "Luziania",
    "Morrinhos",
    "Niteroi",
    "Novo Gama",
    "Planaltina",
    "Rio De Janeiro",
    "Santa Luzia",
    "Santo Antonio Do Descoberto",
    "Santos",
    "Sao Paulo",
    "Senador Canedo",
    "Trindade",
    "Valparaiso De Goias",
  ],
  CTV: ["Via Embratel"],
  MAISSP: [
    "Almenara",
    "Almirante Tamandare",
    "Aparecida De Goiania",
    "Aracaju",
    "Aracruz",
    "Araguaina",
    "Araguari",
    "Araucaria",
    "Araxa",
    "Arcos",
    "Ariquemes",
    "Artur Nogueira",
    "Bady Bassitt",
    "Balneario Camboriu",
    "Barbacena",
    "Barra Do Pirai",
    "Barra Dos Coqueiros",
    "Bauru",
    "Bebedouro",
    "Betim",
    "Bom Jardim",
    "Brasilia De Minas",
    "Brusque",
    "Cabedelo",
    "Cachoeiro De Itapemirim",
    "Cacoal",
    "Cajamar",
    "Camacari",
    "Campina Grande",
    "Campinas",
    "Campo Bom",
    "Campo Grande",
    "Campo Largo",
    "Campos Dos Goytacazes",
    "Canoas",
    "Capelinha",
    "Caratinga",
    "Cariacica",
    "Caruaru",
    "Casimiro De Abreu",
    "Cataguases",
    "Colatina",
    "Colombo",
    "Conselheiro Lafaiete",
    "Contagem",
    "Cosmopolis",
    "Curvelo",
    "Diamantina",
    "Divinopolis",
    "Dourados",
    "Esmeraldas",
    "Estancia Velha",
    "Esteio",
    "Eunapolis",
    "Feira De Santana",
    "Fernandopolis",
    "Formiga",
    "Franca",
    "Gaspar",
    "Governador Valadares",
    "Gravatai",
    "Guabiruba",
    "Guaira",
    "Guapiacu",
    "Guararapes",
    "Guaxupe",
    "Gurupi",
    "Ibate",
    "Igrejinha",
    "Ilheus",
    "Indaiatuba",
    "Ipatinga",
    "Itabaiana",
    "Itabuna",
    "Itajai",
    "Itamarandiba",
    "Itapema",
    "Itapetinga",
    "Itaquaquecetuba",
    "Itauna",
    "Ituiutaba",
    "Jaboticabal",
    "Jacobina",
    "Jardinopolis",
    "Jaru",
    "Jequie",
    "Ji-Parana",
    "Joao Monlevade",
    "Jose Bonifacio",
    "Juiz De Fora",
    "Jundiai",
    "Lagoa Da Prata",
    "Lagoa Santa",
    "Lencois Paulista",
    "Leopoldina",
    "Macae",
    "Mage",
    "Manhuacu",
    "Maracaju",
    "Mariana",
    "Marica",
    "Mata De Sao Joao",
    "Matozinhos",
    "Miguel Pereira",
    "Mirandopolis",
    "Monte Alto",
    "Monte Carmelo",
    "Montes Claros",
    "Morungaba",
    "Muriae",
    "Navegantes",
    "Navirai",
    "Nova Friburgo",
    "Nova Lima",
    "Nova Serrana",
    "Olimpia",
    "Ouro Preto",
    "Ouro Preto Do Oeste",
    "Palhoca",
    "Palmas",
    "Para De Minas",
    "Paracatu",
    "Paraiba Do Sul",
    "Paraiso Do Tocantins",
    "Passos",
    "Patos De Minas",
    "Patrocinio",
    "Paulinia",
    "Pedro Leopoldo",
    "Petropolis",
    "Pimenta Bueno",
    "Pinhais",
    "Pinheiral",
    "Piracicaba",
    "Pirai",
    "Piumhi",
    "Poa",
    "Ponta Pora",
    "Pontal",
    "Ponte Nova",
    "Porto Nacional",
    "Porto Seguro",
    "Porto Velho",
    "Potirendaba",
    "Presidente Prudente",
    "Promissao",
    "Ribeirao Das Neves",
    "Ribeirao Pires",
    "Ribeirao Preto",
    "Rio Branco",
    "Rio Das Ostras",
    "Rolim De Moura",
    "Rondonopolis",
    "Sabara",
    "Sacramento",
    "Santa Cruz Das Palmeiras",
    "Santa Cruz De Minas",
    "Santa Rosa De Viterbo",
    "Sao Carlos",
    "Sao Goncalo",
    "Sao Joao Del Rei",
    "Sao Jose",
    "Sao Jose Do Rio Preto",
    "Sao Jose Dos Pinhais",
    "Sao Leopoldo - Cabo",
    "Sao Mateus",
    "Sao Sebastiao Do Paraiso",
    "Sapiranga",
    "Sapucaia Do Sul",
    "Serra",
    "Sete Lagoas",
    "Silva Jardim",
    "Simoes Filho",
    "Suzano",
    "Tambau",
    "Teixeira De Freitas",
    "Teofilo Otoni",
    "Teresopolis",
    "Tres Rios",
    "Uberaba",
    "Uberlandia",
    "Unai",
    "Valenca",
    "Valparaiso",
    "Vassouras",
    "Vespasiano",
    "Vicosa",
    "Vilhena",
    "Vitoria Da Conquista",
    "Volta Redonda",
    "Votuporanga",
  ],
  SUL: [
    "Alfenas",
    "Alvorada",
    "Andira",
    "Apucarana",
    "Arapongas",
    "Araquari",
    "Ararangua",
    "Arroio Do Meio",
    "Aruja",
    "Astorga",
    "Bage",
    "Barra Do Garcas",
    "Batatais",
    "Bento Goncalves",
    "Biguacu",
    "Blumenau",
    "Blumenau Btv",
    "Cabo Frio",
    "Cachoeirinha",
    "Caieiras",
    "Camaqua",
    "Cambe",
    "Campina Grande Do Sul",
    "Campo Magro",
    "Campo Mourao",
    "Canela",
    "Capao Da Canoa",
    "Carazinho",
    "Carlos Barbosa",
    "Castanhal",
    "Castro",
    "Catanduva",
    "Caxambu",
    "Caxias Do Sul",
    "Chapeco - Old",
    "Charqueadas",
    "Concordia",
    "Cornelio Procopio",
    "Coronel Fabriciano",
    "Criciuma",
    "Cruz Alta",
    "Curitiba - Cabo",
    "Curitiba - Mmds",
    "Dois Irmaos",
    "Dracena",
    "Eldorado Do Sul",
    "Encantado",
    "Erechim",
    "Estrela",
    "Extrema",
    "Farroupilha",
    "Fazenda Rio Grande",
    "Flores Da Cunha",
    "Floresta",
    "Florianopolis",
    "Foz Do Iguacu",
    "Francisco Beltrao",
    "Frederico Westphalen",
    "Garibaldi",
    "Garopaba",
    "Gramado",
    "Guaramirim",
    "Guaratuba",
    "Ibipora",
    "Ibiuna",
    "Icara",
    "Imbe",
    "Itajuba",
    "Itaqui",
    "Itatiba",
    "Ituporanga",
    "Ivoti",
    "Jandaia Do Sul",
    "Jaragua Do Sul",
    "Joacaba",
    "Joinville",
    "Lages",
    "Lajeado",
    "Lavras",
    "Londrina",
    "Louveira",
    "Macapa",
    "Maraba",
    "Marau",
    "Maringa",
    "Matinhos",
    "Montenegro",
    "Nova Odessa",
    "Nova Petropolis",
    "Novo Hamburgo - Cabo",
    "Novo Hamburgo - Mmds",
    "Osorio",
    "Paicandu",
    "Palmas",
    "Palmeira Das Missoes",
    "Panambi",
    "Paranagua",
    "Parauapebas",
    "Passo Fundo",
    "Pato Branco",
    "Pelotas",
    "Piraquara",
    "Pocos De Caldas",
    "Porto Alegre - Cabo",
    "Porto Alegre - Mmds",
    "Pouso Alegre",
    "Quatro Barras",
    "Ribeirao Do Pinhal",
    "Rio Do Sul",
    "Rio Grande",
    "Rio Pardo",
    "Rio Verde",
    "Rolandia",
    "Rosario Do Sul",
    "Santa Cruz Do Sul",
    "Santa Helena De Goias",
    "Santa Maria",
    "Santa Rita Do Sapucai",
    "Santa Rosa",
    "Santana",
    "Santiago",
    "Sao Borja",
    "Sao Francisco Do Sul",
    "Sao Gabriel",
    "Sao Leopoldo - Mmds",
    "Sao Lourenco",
    "Sao Lourenco Do Sul",
    "Sao Luiz Gonzaga",
    "Sao Miguel Arcanjo",
    "Sao Pedro Da Aldeia",
    "Sao Pedro Do Ivai",
    "Sao Roque",
    "Sao Sebastiao Da Amoreira",
    "Saquarema",
    "Sarandi",
    "Sinop",
    "Sobral",
    "Sorriso",
    "Tatui",
    "Teutonia",
    "Timbo",
    "Torres",
    "Tramandai",
    "Tremembe",
    "Tres Coracoes",
    "Tres Coroas",
    "Tres De Maio",
    "Tubarao",
    "Umuarama",
    "Uniao Da Vitoria",
    "Uruguaiana",
    "Varginha",
    "Varzea Paulista",
    "Venancio Aires",
    "Vera Cruz",
    "Veranopolis",
    "Viamao",
    "Vinhedo",
    "Votorantim",
    "Wenceslau Braz",
    "Xangri-La",
  ],
  SOC: [
    "Adamantina",
    "Agudos",
    "Alagoinhas",
    "Alegrete",
    "Aluminio",
    "Alvares Machado",
    "Ananindeua",
    "Aparecida",
    "Aquiraz",
    "Arapiraca",
    "Arraial Do Cabo",
    "Assis",
    "Avare",
    "Barra Bonita",
    "Barreiras",
    "Barretos",
    "Barueri",
    "Belem",
    "Belford Roxo",
    "Botucatu",
    "Cacador",
    "Caceres",
    "Cachoeira Do Sul",
    "Cachoeira Paulista",
    "Camboriu",
    "Campo Limpo Paulista",
    "Capivari",
    "Carapicuiba",
    "Casa Branca",
    "Cascavel",
    "Caucaia",
    "Caxias",
    "Cerquilho",
    "Chapeco",
    "Cianorte",
    "Corumba",
    "Cotia",
    "Cruzeiro",
    "Cuiaba",
    "Duque De Caxias",
    "Elias Fausto",
    "Embu Das Artes",
    "Embu-Guacu",
    "Eusebio",
    "Floriano",
    "Fortaleza",
    "Fraiburgo",
    "Garanhuns",
    "Garca",
    "Guaiba",
    "Guarapari",
    "Guarapuava",
    "Guaratingueta",
    "Guarulhos",
    "Herval Doeste",
    "Igaracu Do Tiete",
    "Iguatu",
    "Ijui",
    "Imperatriz",
    "Indaial",
    "Itaguai",
    "Itapecerica Da Serra",
    "Itapevi",
    "Itupeva",
    "Jandira",
    "Jau",
    "Joao Pessoa",
    "Juazeiro",
    "Juazeiro Do Norte",
    "Juina",
    "Laranjal Paulista",
    "Lauro De Freitas",
    "Linhares",
    "Lorena",
    "Luis Eduardo Magalhaes",
    "Maceio",
    "Mafra",
    "Maracanau",
    "Marechal Candido Rondon",
    "Marechal Deodoro",
    "Marilia",
    "Medianeira",
    "Mesquita",
    "Mococa",
    "Monte Mor",
    "Mossoro",
    "Natal",
    "Nilopolis",
    "Nova Iguacu",
    "Nova Venecia",
    "Osasco",
    "Paco Do Lumiar",
    "Paracambi",
    "Paragominas",
    "Parnaiba",
    "Parnamirim",
    "Parobe",
    "Paulo Afonso",
    "Piedade",
    "Piripiri",
    "Ponta Grossa",
    "Pontes E Lacerda",
    "Porto Feliz",
    "Porto Ferreira",
    "Potim",
    "Presidente Bernardes",
    "Primavera Do Leste",
    "Queimados",
    "Rafard",
    "Registro",
    "Rio Negrinho",
    "Salto",
    "Salvador",
    "Santa Ines",
    "Santana De Parnaiba",
    "Santana Do Livramento",
    "Santarem",
    "Santo Angelo",
    "Sao Bento Do Sul",
    "Sao Gabriel Da Palha",
    "Sao Joao De Meriti",
    "Sao Jose De Ribamar",
    "Sao Jose Do Rio Pardo",
    "Sao Luis",
    "Senhor Do Bonfim",
    "Serrana",
    "Sertaozinho",
    "Sorocaba",
    "Taboao Da Serra",
    "Tangara Da Serra",
    "Taquara",
    "Telemaco Borba",
    "Teresina",
    "Tiete",
    "Timon",
    "Toledo",
    "Tupa",
    "Uba",
    "Vacaria",
    "Valenca",
    "Valinhos",
    "Vargem Grande Paulista",
    "Varzea Grande",
    "Vera Cruz",
    "Viana",
    "Videira",
    "Vila Velha",
    "Vitoria",
    "Xanxere",
    "Xaxim",
  ],
};
export default cidadesAtlas;
